# clone directory
clone_folder: C:\NitraBase\Nitra\


environment:
  NemerleBinPathRoot: C:\Program Files (x86)\Nemerle\
  NitraPath: C:\NitraBase\Nitra\
  NuGet: C:\NitraBase\Nitra\ExternalTools\NuGet.exe

platform: Mixed Platforms
configuration: Debug
  
install:
# Note: Configuration ==      Debug        hardcoded, dynamicly didn't work on the buildserver
  - nuget sources add -Name NitraLocal -Source "C:\NitraBase\Nitra\bin\Debug\NuGetSource"
  - ps: C:\NitraBase\Nitra\appveyor_prepare.ps1
  - C:\NitraBase\Nitra\Nitra\BuildBoot.cmd <nul
  
before_build:
  - nuget restore Nitra.sln

build:
  parallel: true
  project: Nitra.sln
  verbosity: normal

# off avoids automatic nunit test execution of dependecies loaded via nuget...
test: off
  
artifacts:
  - path: bin\$(configuration)
    name: NitraBin
  - path: 'Nitra\Boot1\Net-4.0'
    name: Boot1
  - path: 'Nitra\Boot2\Net-4.0'
    name: Boot2
  - path: Nitra.LanguageCompiler\bin\$(configuration)
    name: LanguageCompiler
  - path: Nitra.TestsLauncher\bin\$(configuration)
    name: TestsLauncher
  - path: Nitra.Visualizer\bin\$(configuration)
    name: Visualizer
  - path: Grammars\Bin\$(configuration)
    name: Grammars